# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."TFG" = {
    image = "itzg/minecraft-server:latest";
    environment = {
      "ENABLE_RCON" = "false";
      "EULA" = "true";
      "FORGE_VERSION" = "47.4.13";
      "GENERIC_PACKS" = "TerraFirmaGreg-Modern-0.12.6-serverpack";
      "GENERIC_PACKS_PREFIX" = "https://github.com/TerraFirmaGreg-Team/Modpack-Modern/releases/download/0.12.6/";
      "GENERIC_PACKS_SUFFIX" = ".zip";
      "GUI" = "false";
      "MEMORY" = "6G";
      "OVERRIDE_SERVER_PROPERTIES" = "false";
      "SKIP_GENERIC_PACK_UPDATE_CHECK" = "true";
      "TYPE" = "forge";
      "VERSION" = "1.20.1";
    };
    volumes = [
      "/home/kin/data/minecraft/TFG:/data:rw"
      "/home/kin/data/minecraft/TFG/backups:/backups:rw"
    ];
    ports = [
      "6789:25565/tcp"
      "24454:24454/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=terrafirmagreg-modern"
      "--network=services_default"
    ];
  };
  systemd.services."podman-TFG" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."lavalink" = {
    image = "ghcr.io/lavalink-devs/lavalink:latest";
    environment = {
      "LAVALINK_SERVER_PASSWORD" = "youshallnotpass";
      "SERVER_PORT" = "2333";
    };
    volumes = [
      "/home/kin/data/vocard-bot/lavalink/application.yml:/opt/Lavalink/application.yml:rw"
      "/home/kin/data/vocard-bot/lavalink/logs:/opt/Lavalink/logs:rw"
      "/home/kin/data/vocard-bot/lavalink/plugins:/opt/Lavalink/plugins:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=lavalink"
      "--network=vocard"
    ];
  };
  systemd.services."podman-lavalink" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-vocard.service"
    ];
    requires = [
      "podman-network-vocard.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."multi-scrobbler" = {
    image = "foxxmd/multi-scrobbler:latest";
    environment = {
      "BASE_URL" = "http://192.168.0.122:9078";
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/home/kin/data/multi-scrobbler/config:/config:rw"
    ];
    ports = [
      "9078:9078/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=multi-scrobbler"
      "--network=services_default"
    ];
  };
  systemd.services."podman-multi-scrobbler" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."recyclarr" = {
    image = "ghcr.io/recyclarr/recyclarr:8";
    environment = {
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/home/kin/data/recyclarr:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=recyclarr"
      "--network=services_default"
    ];
  };
  systemd.services."podman-recyclarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."services-fourget" = {
    image = "luuul/4get:latest";
    environment = {
      "FOURGET_PROTO" = "http";
      "FOURGET_SERVER_NAME" = "4get.peanutbutter.quest";
    };
    ports = [
      "10030:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=fourget"
      "--network=services_default"
    ];
  };
  systemd.services."podman-services-fourget" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."services-mc" = {
    image = "itzg/minecraft-server:latest";
    environment = {
      "DIFFICULTY" = "2";
      "ENABLE_AUTOPAUSE" = "false";
      "ENFORCE_SECURE_PROFILE" = "false";
      "EULA" = "TRUE";
      "MEMORY" = "3072M";
      "MODS" = "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
  https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
  https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/5.7.2/PAPER/ViaBackwards-5.7.2.jar
  https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.7.2/PAPER/ViaVersion-5.7.2.jar
  https://cdn.modrinth.com/data/7pdfxYHV/versions/7JPEmS9o/instantrestock_2.6.1.jar
  https://cdn.modrinth.com/data/1u6JkXh5/versions/JUWRHdru/worldedit-bukkit-7.4.1.jar";
      "ONLINE_MODE" = "false";
      "SEED" = "-7723232821704547830";
      "SIMULATION_DISTANCE" = "12";
      "TYPE" = "PAPER";
      "TZ" = "Asia/Kolkata";
      "USE_AIKAR_FLAGS" = "true";
      "USE_MEOWICE_FLAGS" = "true";
      "USE_SIMD_FLAGS" = "true";
      "VIEW_DISTANCE" = "12";
    };
    volumes = [
      "/home/kin/data/minecraft/vanilla:/data:rw"
    ];
    ports = [
      "25565:25565/tcp"
      "25565:25565/udp"
      "19132:19132/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mc"
      "--network=services_default"
    ];
  };
  systemd.services."podman-services-mc" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."spotify-tokener" = {
    image = "ghcr.io/topi314/spotify-tokener:master";
    environment = {
      "SPOTIFY_TOKENER_ADDR" = "0.0.0.0:49152";
    };
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=nc -z -v localhost 49152"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=spotify-tokener"
      "--network=vocard"
    ];
  };
  systemd.services."podman-spotify-tokener" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-vocard.service"
    ];
    requires = [
      "podman-network-vocard.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."vocard" = {
    image = "ghcr.io/chocomeow/vocard:beta";
    volumes = [
      "/home/kin/data/vocard-bot/settings.json:/app/settings.json:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=vocard"
      "--network=vocard"
    ];
  };
  systemd.services."podman-vocard" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-vocard.service"
    ];
    requires = [
      "podman-network-vocard.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."vocard-dashboard" = {
    image = "ghcr.io/chocomeow/vocard-dashboard:latest";
    volumes = [
      "/home/kin/data/vocard-bot/dashboard/settings.json:/app/settings.json:rw"
    ];
    ports = [
      "10050:10050/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"python\", \"-c\", \"import urllib.request; urllib.request.urlopen('http://localhost:10050/health').read()\"]"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-start-period=10s"
      "--health-timeout=5s"
      "--network-alias=vocard-dashboard"
      "--network=vocard"
    ];
  };
  systemd.services."podman-vocard-dashboard" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-vocard.service"
    ];
    requires = [
      "podman-network-vocard.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."vocard-db" = {
    image = "mongo:8";
    environment = {
      "MONGO_INITDB_ROOT_PASSWORD" = "admin";
      "MONGO_INITDB_ROOT_USERNAME" = "admin";
    };
    volumes = [
      "/home/kin/data/vocard-bot/mongodb_data:/data/db:rw"
    ];
    cmd = [ "mongod" "--oplogSize=1024" "--wiredTigerCacheSizeGB=1" "--auth" "--noscripting" ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-start-period=10s"
      "--health-timeout=5s"
      "--network-alias=vocard-db"
      "--network=vocard"
    ];
  };
  systemd.services."podman-vocard-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-vocard.service"
    ];
    requires = [
      "podman-network-vocard.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."yt-cipher" = {
    image = "ghcr.io/kikkia/yt-cipher:master";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=yt-cipher"
      "--network=vocard"
    ];
  };
  systemd.services."podman-yt-cipher" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-vocard.service"
    ];
    requires = [
      "podman-network-vocard.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-services_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f services_default";
    };
    script = ''
      podman network inspect services_default || podman network create services_default
    '';
    partOf = [ "podman-compose-services-root.target" ];
    wantedBy = [ "podman-compose-services-root.target" ];
  };
  systemd.services."podman-network-vocard" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f vocard";
    };
    script = ''
      podman network inspect vocard || podman network create vocard
    '';
    partOf = [ "podman-compose-services-root.target" ];
    wantedBy = [ "podman-compose-services-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-services-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
