# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."kasmcord" = {
    image = "kasmweb/discord:1.14.0";
    environment = {
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
      "VNC_PW" = "hunter2";
      "XDG_RUNTIME_DIR" = "/run/user/1000";
    };
    volumes = [
      "/home/kin/data/multi-scrobbler/discord/config:/home/kasm-user/.config:rw"
      "/home/kin/data/multi-scrobbler/discord/run:/run/user/1000:rw"
    ];
    ports = [
      "6901:6901/tcp"
    ];
    user = "0";
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"sh\", \"-c\", \"chmod 700 /run/user/1000 && chown -R kasm-user:kasm-user /run/user/1000 && chown -R kasm-user:kasm-user /home/kasm-user/.config && su kasm-user -c '/dockerstartup/kasm_default_profile.sh /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh'\"]"
      "--network-alias=kasmcord"
      "--network=services_default"
      "--shm-size=536870912"
    ];
  };
  systemd.services."podman-kasmcord" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."multi-scrobbler" = {
    image = "foxxmd/multi-scrobbler:latest";
    environment = {
      "BASE_URL" = "http://192.168.0.122:9078";
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/home/kin/data/multi-scrobbler/config:/config:rw"
      "/home/kin/data/multi-scrobbler/discord/run:/run:rw"
    ];
    ports = [
      "9078:9078/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=multi-scrobbler"
      "--network=services_default"
    ];
  };
  systemd.services."podman-multi-scrobbler" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."piped-backend" = {
    image = "1337kavin/piped:latest";
    volumes = [
      "/home/kin/Piped-Docker/config/config.properties:/app/config.properties:ro"
    ];
    ports = [
      "7071:8080/tcp"
    ];
    dependsOn = [
      "piped-postgres"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=piped"
      "--network=services_default"
    ];
  };
  systemd.services."podman-piped-backend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."piped-bg-helper" = {
    image = "1337kavin/bg-helper-server:latest";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=bg-helper"
      "--network=services_default"
    ];
  };
  systemd.services."podman-piped-bg-helper" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."piped-frontend" = {
    image = "1337kavin/piped-frontend:latest";
    environment = {
      "BACKEND_HOSTNAME" = "pipedapi.ricepaddle.site";
      "HTTP_MODE" = "https";
      "PGID" = "0";
      "PUID" = "0";
    };
    ports = [
      "7070:80/tcp"
    ];
    dependsOn = [
      "piped-backend"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_BIND_SERVICE"
      "--network-alias=frontend"
      "--network=services_default"
      "--privileged"
    ];
  };
  systemd.services."podman-piped-frontend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."piped-postgres" = {
    image = "pgautoupgrade/pgautoupgrade:16-alpine";
    environment = {
      "POSTGRES_DB" = "piped";
      "POSTGRES_PASSWORD" = "changeme";
      "POSTGRES_USER" = "piped";
    };
    volumes = [
      "/home/kin/Piped-Docker/data/db:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=postgres"
      "--network=services_default"
    ];
  };
  systemd.services."podman-piped-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."piped-proxy" = {
    image = "1337kavin/piped-proxy:latest";
    ports = [
      "7072:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=proxy"
      "--network=services_default"
    ];
  };
  systemd.services."podman-piped-proxy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."recyclarr" = {
    image = "ghcr.io/recyclarr/recyclarr:8";
    environment = {
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/home/kin/data/recyclarr:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=recyclarr"
      "--network=services_default"
    ];
  };
  systemd.services."podman-recyclarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."services-mc" = {
    image = "itzg/minecraft-server:latest";
    environment = {
      "DIFFICULTY" = "2";
      "ENABLE_AUTOPAUSE" = "false";
      "ENFORCE_SECURE_PROFILE" = "false";
      "EULA" = "TRUE";
      "MEMORY" = "3072M";
      "MODS" = "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
  https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
  https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/5.7.2/PAPER/ViaBackwards-5.7.2.jar
  https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.7.2/PAPER/ViaVersion-5.7.2.jar
  https://cdn.modrinth.com/data/7pdfxYHV/versions/7JPEmS9o/instantrestock_2.6.1.jar
  https://cdn.modrinth.com/data/1u6JkXh5/versions/JUWRHdru/worldedit-bukkit-7.4.1.jar";
      "ONLINE_MODE" = "false";
      "SEED" = "-7723232821704547830";
      "SIMULATION_DISTANCE" = "12";
      "TYPE" = "PAPER";
      "TZ" = "Asia/Kolkata";
      "USE_AIKAR_FLAGS" = "true";
      "USE_MEOWICE_FLAGS" = "true";
      "USE_SIMD_FLAGS" = "true";
      "VIEW_DISTANCE" = "12";
    };
    volumes = [
      "/home/kin/data/minecraft/vanilla:/data:rw"
    ];
    ports = [
      "25565:25565/tcp"
      "25565:25565/udp"
      "19132:19132/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mc"
      "--network=services_default"
    ];
  };
  systemd.services."podman-services-mc" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."terrafirmagreg-modern" = {
    image = "itzg/minecraft-server:latest";
    environment = {
      "ENABLE_RCON" = "true";
      "EULA" = "true";
      "FORGE_VERSION" = "47.4.13";
      "GENERIC_PACKS" = "TerraFirmaGreg-Modern-0.11.27-serverpack";
      "GENERIC_PACKS_PREFIX" = "https://github.com/TerraFirmaGreg-Team/Modpack-Modern/releases/download/0.11.27/";
      "GENERIC_PACKS_SUFFIX" = ".zip";
      "GUI" = "false";
      "MEMORY" = "6G";
      "OVERRIDE_SERVER_PROPERTIES" = "false";
      "SKIP_GENERIC_PACK_UPDATE_CHECK" = "true";
      "TYPE" = "forge";
      "VERSION" = "1.20.1";
    };
    volumes = [
      "/home/kin/data/minecraft/TFG:/data:rw"
      "/home/kin/data/minecraft/TFG/backups:/backups:rw"
    ];
    ports = [
      "6789:25565/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=TFG"
      "--network=services_default"
    ];
  };
  systemd.services."podman-terrafirmagreg-modern" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-services_default.service"
    ];
    requires = [
      "podman-network-services_default.service"
    ];
    partOf = [
      "podman-compose-services-root.target"
    ];
    wantedBy = [
      "podman-compose-services-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-services_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f services_default";
    };
    script = ''
      podman network inspect services_default || podman network create services_default
    '';
    partOf = [ "podman-compose-services-root.target" ];
    wantedBy = [ "podman-compose-services-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-services-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
